#lang racket

;;;; A bunch of things

(provide variables functions ncomplr-specials ncomplr-arrays)

(define ncomplr-arrays
  '(("A1S1A")
    ("AC-ADDRS")
    ("PDL-ADDRS")
    ("STGET")
    ("BOLA")
    ("CBA")
    ("PVIA")))

(define ncomplr-specials
  '(("+INTERNAL-WITHOUT-INTERRUPTS")
    ("+INTERNAL-INTERRUPT-BOUND-VARIABLES")
    ("ACSMODE")
    ("ARGLOC")
    ("ARGNO")
    ("ARITHP")
    ("ARRAYOPEN")
    ("ASSEMBLE")
    ("ATPL")
    ("ATPL1")
    ("BVARS")
    ("CAAGL")
    ("CARCDR")
    ("CCLOAD:INITIAL-PROPS")
    ("CDMACSVERNO")
    ("CDUMP")
    ("CFVFL")
    ("CHOMPHOOK")
    ("CL")
    ("CLEANUPSPL")
    ("CLOSED")
    ("CLPROGN")
    ("CMSGFILES")
    ("CNT")
    ("COBARRAY")
    ("COMAL")
    ("COMAUXVERNO")
    ("COMP")
    ("COMPILATION-FLAGCONVERSION-TABLE")
    ("COMPILER-STAT")
    ("COMPLRVERNO")
    ("CONDP")
    ("CONDPNOB")
    ("CONDTYPE")
    ("CONDUNSF")
    ("CREADTABLE")
    ("CTAG")
    ("DATA")
    ("DISOWNED")
    ("EFFS")
    ("EOC-EVAL")
    ("EOF-COMPILE-QUEUE")
    ("EOF-SEEN")
    ("ERRFL")
    ("EXIT")
    ("EXITN")
    ("EXLDL")
    ("EXPAND-OUT-MACROS")
    ("EXPR-HASH")
    ("EXTEND-FILES-TO-LOAD")
    ("FASL")
    ("FASLPUSH")
    ("FBARP")
    ("FILEPOSIBLE")
    ("FILESCLOSEP")
    ("FIXSW")
    ("FLOSW")
    ("FLPDL")
    ("FXPDL")
    ("GAG-ERRBREAKS")
    ("GENPREFIX")
    ("GFYC")
    ("GL")
    ("GOBRKL")
    ("GOFOO")
    ("GONE2")
    ("HLAC")
    ("HUNK2-TO-CONS")
    ("IDENTITY")
    ("IGNOREVARS")
    ("IMOSAR")
    ("INFILE")
    ("INITIALIZE")
    ("INITIAVERNO")
    ("INMLS")
    ("INSTACK")
    ("IOBARRAY")
    ("IREADTABLE")
    ("KTYPE")
    ("L-END-CNT")
    ("LAP-INSIGNIF")
    ("LAPLL")
    ("LAPOF")
    ("LDLST")
    ("LERSTP+1")
    ("LINEL")
    ("LINEMODEP")
    ("LMBP")
    ("LOCVARS")
    ("LOUT")
    ("LOUT1")
    ("LPASST-FXP")
    ("LPASST-P+1")
    ("LPRSL")
    ("MACROLIST")
    ("MACROS")
    ("MAKLAP-DEFAULTF-STYLE")
    ("MAKLAPVERNO")
    ("MAKUNBOUND")
    ("MAPEX")
    ("MAPSB")
    ("MCX-TRACE")
    ("MODELIST")
    ("MSDEV")
    ("MSDIR")
    ("MUZZLED")
    ("NEW-EXTEND-FILES-TO-LOAD")
    ("NLNVS")
    ("NLNVTHTBP")
    ("NOLAP")
    ("NULFU")
    ("NUMACS")
    ("OLVRL")
    ("ONMLS")
    ("OPSYS")
    ("OPVRL")
    ("OUTFILES")
    ("P1CCX")
    ("P1CSQ")
    ("P1GFY")
    ("P1LL")
    ("P1LLCEK")
    ("P1LSQ")
    ("P1PCX")
    ("P1PSQ")
    ("P1SPECIALIZEDVS")
    ("P2P")
    ("PHAS1VERNO")
    ("PKTYP")
    ("PNOB")
    ("PRATTSTACK")
    ("PROGN")
    ("PROGP")
    ("PROGTYPE")
    ("PROGUNSF")
    ("PRSSL")
    ("PVR")
    ("PVRL")
    ("QSM")
    ("QUIT-ON-ERROR")
    ("READ")
    ("RECOMPL")
    ("REGACS")
    ("REGPDL")
    ("RNL")
    ("ROSENCEK")
    ("RUNTIME-LIMIT")
    ("RUNTIME-LIMITP")
    ("SAIL-MORE-SYSFUNS")
    ("SAVED-ERRLIST")
    ("SFLG")
    ("SLOTX")
    ("SOBARRAY")
    ("SPECIAL")
    ("SPECIALS")
    ("SPECVARS")
    ("SPLDLST")
    ("SPLITFILE-HOOK")
    ("SQUID")
    ("SREADTABLE")
    ("STATE")
    ("STSL")
    ("SWITCHLIST")
    ("SWITCHTABLE")
    ("SYMBOLS")
    ("TAKENAC1")
    ("TOPFN")
    ("TTYNOTES")
    ("TYO")
    ("UNDFUNS")
    ("UNFASLCOMMENTS")
    ("UNSFLST")
    ("UREAD")
    ("USE-STRT7")
    ("USERATOMS-HOOKS")
    ("USERATOMS-INTERN")
    ("USERATOMS-INTERN-FROB")
    ("USER-STRING-MARK-IN-FASL")
    ("UWRITE")
    ("VGO")
    ("VGOL")
    ("VL")
    ("YESWARNTTY")
    ("ALLATOMS")
    ("AMBIGSYMS")
    ("ATOMINDEX")
    ("BINCT")
    ("CURRENTFN")
    ("CURRENTFNSYMS")
    ("DDTSYMP")
    ("DDTSYMS")
    ("ENTRYNAMES")
    ("EXPR")
    ("FASLEVAL")
    ("FASLPUSH")
    ("FASLVERNO")
    ("FILOC")
    ("FSLFLD")
    ("IMOBFL")
    ("IMOSAR")
    ("IMOUSR")
    ("LASTENTRY")
    ("LDFNM")
    ("LITCNT")
    ("LITERALP")
    ("LITERALS")
    ("LITLOC")
    ("*LOC")
    ("MAINSYMPDL")
    ("MAKUNBOUND")
    ("MESSIOC")
    ("MSDIR")
    ("SQUIDP")
    ("SYMBOLSP")
    ("SYMPDL")
    ("UFFIL")
    ("UNDEFSYMS")
    ("UNFASLCOMMENTS")
    ("UNFASLSIGNIF")
    ("TYPE-PRED")
    ("KEYFORM")))

(define variables
  '(("ALARMCLOCK" . "https://maclisp.info/pitmanual/system.html#24.3.2")
    ("AUTOLOAD" . "https://maclisp.info/pitmanual/error.html#21.8")
    ("^A" . "https://maclisp.info/pitmanual/system.html#24.1.4")
    ("BACKQUOTE-EXPAND-WHEN" . "https://maclisp.info/pitmanual/syntax.html#20.29.1")
    ("BASE" . "https://maclisp.info/pitmanual/io.html#16.3.7")
    ("BPEND" . "https://maclisp.info/pitmanual/system.html#24.30.2")
    ("BPORG" . "https://maclisp.info/pitmanual/system.html#24.30.1")
    ("CAR" . "https://maclisp.info/pitmanual/list.html#8.17.1")
    ("|carcdrp/||" . "https://maclisp.info/pitmanual/intrnl.html#26.9.5")
    ("CDR" . "https://maclisp.info/pitmanual/list.html#8.17.2")
    ("CLI-MESSAGE" . "https://maclisp.info/pitmanual/system.html#24.2.1")
    ("COMPILER-STATE" . "https://maclisp.info/pitmanual/complr.html#23.1.7")
    ("DEFAULTF" . "https://maclisp.info/pitmanual/files.html#19.3.2")
    ("DEFMACRO-CHECK-ARGS" . "https://maclisp.info/pitmanual/def.html#7.6.1")
    ("DEFMACRO-DISPLACE-CALL" . "https://maclisp.info/pitmanual/def.html#7.6.2")
    ("DEFMACRO-FOR-COMPILING" . "https://maclisp.info/pitmanual/def.html#7.6.3")
    ("DEFUN&amp;-CHECK-ARGS" . "https://maclisp.info/pitmanual/def.html#7.10.2")
    ("^D" . "https://maclisp.info/pitmanual/system.html#24.18.11")
    ("ECHOFILES" . "https://maclisp.info/pitmanual/io.html#16.3.4")
    ("EDIT" . "https://maclisp.info/pitmanual/edit.html#25.3.2")
    ("ERRLIST" . "https://maclisp.info/pitmanual/error.html#21.5.1")
    ("ERROR-BREAK-ENVIRONMENT" . "https://maclisp.info/pitmanual/error.html#21.6.2")
    ("ERRSET" . "https://maclisp.info/pitmanual/error.html#21.2.2")
    ("EVAL" . "https://maclisp.info/pitmanual/debug.html#22.13")
    ("EVALHOOK" . "https://maclisp.info/pitmanual/debug.html#22.7.1")
    ("FAIL-ACT" . "https://maclisp.info/pitmanual/error.html#21.3.7")
    ("FASLOAD" . "https://maclisp.info/pitmanual/files.html#19.2.3")
    ("GC-DAEMON" . "https://maclisp.info/pitmanual/system.html#24.18.8")
    ("GC-LOSSAGE" . "https://maclisp.info/pitmanual/error.html#21.3.6")
    ("GC-OVERFLOW" . "https://maclisp.info/pitmanual/system.html#24.18.9")
    ("GCPROTECT" . "https://maclisp.info/pitmanual/system.html#24.18.10")
    ("GCTWA" . "https://maclisp.info/pitmanual/system.html#24.18.4")
    ("GRIND-MACROEXPANDED" . "https://maclisp.info/pitmanual/io.html#16.46.4")
    ("GRINDEF" . "https://maclisp.info/pitmanual/io.html#16.46.5")
    ("HUNKP" . "https://maclisp.info/pitmanual/hunks.html#13.2.2")
    ("IBASE" . "https://maclisp.info/pitmanual/io.html#16.2.5")
    ("INFILE" . "https://maclisp.info/pitmanual/io.html#16.2.2")
    ("INSTACK" . "https://maclisp.info/pitmanual/io.html#16.2.3")
    ("IO-LOSSAGE" . "https://maclisp.info/pitmanual/error.html#21.3.8")
    ("|`-,-level/||" . "https://maclisp.info/pitmanual/intrnl.html#26.16.5")
    ("LINEL" . "https://maclisp.info/pitmanual/io.html#16.5.3")
    ("MACHINE-ERROR" . "https://maclisp.info/pitmanual/error.html#21.4.1")
    ("MACRO-EXPANSION-USE" . "https://maclisp.info/pitmanual/def.html#7.7.1")
    ("/#-MACRO-DATALIST" . "https://maclisp.info/pitmanual/syntax.html#20.28.3")
    ("MACROEXPANDED" . "https://maclisp.info/pitmanual/def.html#7.9.2")
    ("MAKHUNK" . "https://maclisp.info/pitmanual/hunks.html#13.2.1")
    ("MAR-BREAK" . "https://maclisp.info/pitmanual/debug.html#22.9.2")
    ("MSGFILES" . "https://maclisp.info/pitmanual/io.html#16.3.3")
    ("NIL" . "https://maclisp.info/pitmanual/symbol.html#10.3")
    ("*NOPOINT" . "https://maclisp.info/pitmanual/io.html#16.3.9")
    ("NORET" . "https://maclisp.info/pitmanual/system.html#24.30.6")
    ("NOUUO" . "https://maclisp.info/pitmanual/debug.html#22.3.1")
    ("OBARRAY" . "https://maclisp.info/pitmanual/symbol.html#10.9.1")
    ("OUTFILES" . "https://maclisp.info/pitmanual/io.html#16.3.2")
    ("PDL-OVERFLOW" . "https://maclisp.info/pitmanual/error.html#21.4.2")
    ("PRIN1" . "https://maclisp.info/pitmanual/repl.html#4.5.2")
    ("PRINLENGTH" . "https://maclisp.info/pitmanual/io.html#16.3.10")
    ("PRINLEVEL" . "https://maclisp.info/pitmanual/io.html#16.3.11")
    ("PURCLOBRL" . "https://maclisp.info/pitmanual/system.html#24.31.8")
    ("PURCOPY" . "https://maclisp.info/pitmanual/system.html#24.31.5")
    ("PURE" . "https://maclisp.info/pitmanual/system.html#24.31.7")
    ("*PURE" . "https://maclisp.info/pitmanual/system.html#24.31.2")
    ("PUTPROP" . "https://maclisp.info/pitmanual/system.html#24.31.3")
    ("$P" . "https://maclisp.info/pitmanual/repl.html#4.3.3")
    ("^Q" . "https://maclisp.info/pitmanual/io.html#16.2.4")
    ("READ" . "https://maclisp.info/pitmanual/repl.html#4.5.1")
    ("READ-*-EVAL-PRINT" . "https://maclisp.info/pitmanual/repl.html#4.5.4")
    ("READ-EVAL-*-PRINT" . "https://maclisp.info/pitmanual/repl.html#4.5.5")
    ("READ-EVAL-PRINT-*" . "https://maclisp.info/pitmanual/repl.html#4.5.6")
    ("*-READ-EVAL-PRINT" . "https://maclisp.info/pitmanual/repl.html#4.5.3")
    ("READTABLE" . "https://maclisp.info/pitmanual/io.html#16.2.7")  
    ("*RSET-TRAP" . "https://maclisp.info/pitmanual/debug.html#22.2.3")
    ("*RSET" . "https://maclisp.info/pitmanual/debug.html#22.2.1")
    ("SQUID" . "https://maclisp.info/pitmanual/complr.html#23.2.1")
    ("/#-SYMBOLIC-CHARACTERS-TABLE" . "https://maclisp.info/pitmanual/syntax.html#20.28.4")
    ("SYMBOLS" . "https://maclisp.info/pitmanual/intrnl.html#26.8")
    ("SYS-DEATH" . "https://maclisp.info/pitmanual/system.html#24.2.4")
    ("T" . "https://maclisp.info/pitmanual/symbol.html#10.4")
    ("TERPRI" . "https://maclisp.info/pitmanual/io.html#16.3.12")
    ("TTY" . "https://maclisp.info/pitmanual/io.html#16.5.1")
    ("TTY-RETURN" . "https://maclisp.info/pitmanual/system.html#24.2.6")
    ("TTYSCAN-STRINGERS/|" . "https://maclisp.info/pitmanual/io.html#16.2.8")
    ("TYI" . "https://maclisp.info/pitmanual/io.html#16.2.1")
    ("TYO" . "https://maclisp.info/pitmanual/io.html#16.3.1")
    ("UNBND-VRBL" . "https://maclisp.info/pitmanual/error.html#21.3.2")
    ("UNDF-FNCTN" . "https://maclisp.info/pitmanual/error.html#21.3.1")
    ("UNSEEN-GO-TAG" . "https://maclisp.info/pitmanual/error.html#21.3.4")
    ("UREAD" . "https://maclisp.info/pitmanual/oldio.html#18.1.1")
    ("UWRITE" . "https://maclisp.info/pitmanual/oldio.html#18.1.2")
    ("WRNG-NO-ARGS" . "https://maclisp.info/pitmanual/error.html#21.3.5")
    ("WRNG-TYPE-ARG" . "https://maclisp.info/pitmanual/error.html#21.3.3")
    ("^W" . "https://maclisp.info/pitmanual/io.html#16.3.5")
    ("ZFUZZ" . "https://maclisp.info/pitmanual/number.html#9.51.1")
    ("ZUNDERFLOW" . "https://maclisp.info/pitmanual/number.html#9.51.2")
    ("$$" . "https://maclisp.info/pitmanual/edit.html#25.3.3")
    ("$$$" . "https://maclisp.info/pitmanual/edit.html#25.3.4")
    ("$P" . "https://maclisp.info/pitmanual/repl.html#4.3.3")
    ("*" . "https://maclisp.info/pitmanual/repl.html#4.2.1")
    ("*-READ-EVAL-PRINT" . "https://maclisp.info/pitmanual/repl.html#4.5.3")
    ("*NOPOINT" . "https://maclisp.info/pitmanual/io.html#16.3.9")
    ("*PURE" . "https://maclisp.info/pitmanual/system.html#24.31.2")
    ("*RSET" . "https://maclisp.info/pitmanual/debug.html#22.2.1")
    ("*RSET-TRAP" . "https://maclisp.info/pitmanual/debug.html#22.2.3")
    ("+" . "https://maclisp.info/pitmanual/repl.html#4.2.2")
    ("-" . "https://maclisp.info/pitmanual/repl.html#4.2.3")
    ("/#-MACRO-DATALIST" . "https://maclisp.info/pitmanual/syntax.html#20.28.3")
    ("/#-SYMBOLIC-CHARACTERS-TABLE" . "https://maclisp.info/pitmanual/syntax.html#20.28.4")
    ("//" . "https://maclisp.info/pitmanual/error.html#21.5.2")
    ("^A" . "https://maclisp.info/pitmanual/system.html#24.1.4")
    ("^D" . "https://maclisp.info/pitmanual/system.html#24.18.11")
    ("^Q" . "https://maclisp.info/pitmanual/io.html#16.2.4")
    ("^R" . "https://maclisp.info/pitmanual/io.html#16.3.6")
    ("^W" . "https://maclisp.info/pitmanual/io.html#16.3.5")
    ("^^^" . "https://maclisp.info/pitmanual/edit.html#25.3.5")
    ("carcdrp|" . "https://maclisp.info/pitmanual/intrnl.html#26.9.5")
    ("`-,-level|" . "https://maclisp.info/pitmanual/intrnl.html#26.16.5")))

(define functions
  '(("ABS" . "https://www.maclisp.info/pitmanual/number.html#9.42")
    ("ADD1" . "https://www.maclisp.info/pitmanual/number.html#9.7")
    ("ALARMCLOCK" . "https://www.maclisp.info/pitmanual/system.html#24.3.1")
    ("ALLFILES" . "https://www.maclisp.info/pitmanual/files.html#19.6.2")
    ("ALLOC" . "https://www.maclisp.info/pitmanual/system.html#24.17.1")
    ("ALPHALESSP" . "https://www.maclisp.info/pitmanual/symbol.html#10.8.2")
    ("APPEND" . "https://www.maclisp.info/pitmanual/list.html#8.7.1")
    ("*APPEND" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.3")
    ("APPLY" . "https://www.maclisp.info/pitmanual/eval.html#3.8.1")
    ("*APPLY" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.1")
    ("ARG" . "https://www.maclisp.info/pitmanual/def.html#7.3.1")
    ("ARGS" . "https://www.maclisp.info/pitmanual/debug.html#22.12.1")
    ("ARRAY*" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("ARRAY-#-DIMS" . "https://www.maclisp.info/pitmanual/array.html#12.6.2")
    ("ARRAY-DIMENSION-N" . "https://www.maclisp.info/pitmanual/array.html#12.6.3")
    ("ARRAY-TYPE" . "https://www.maclisp.info/pitmanual/array.html#12.6.4")
    ("ARRAYDIMS" . "https://www.maclisp.info/pitmanual/array.html#12.6.1")
    ("*ARRAY" . "https://www.maclisp.info/pitmanual/array.html#12.3.1")
    ("ASCII" . "https://www.maclisp.info/pitmanual/charac.html#11.2.1")
    ("ASH" . "https://www.maclisp.info/pitmanual/bits.html#15.4.2")
    ("ASSOC" . "https://www.maclisp.info/pitmanual/list.html#8.8.1")
    ("ASSQ" . "https://www.maclisp.info/pitmanual/list.html#8.8.2")
    ("ATAN" . "https://www.maclisp.info/pitmanual/number.html#9.49.1")
    ("ATOM" . "https://www.maclisp.info/pitmanual/typep.html#2.2.2")
    ("BAKLIST" . "https://www.maclisp.info/pitmanual/debug.html#22.4.1")
    ("BAKTRACE" . "https://www.maclisp.info/pitmanual/debug.html#22.4.2")
    ("BIGP" . "https://www.maclisp.info/pitmanual/number.html#9.3.3")
    ("BIT-CLEAR" . "https://www.maclisp.info/pitmanual/bits.html#15.3.3")
    ("BIT-SET" . "https://www.maclisp.info/pitmanual/bits.html#15.3.2")
    ("BIT-TEST" . "https://www.maclisp.info/pitmanual/bits.html#15.3.1")
    ("BOOLE" . "https://www.maclisp.info/pitmanual/bits.html#15.1.1")
    ("BOUNDP" . "https://www.maclisp.info/pitmanual/symbol.html#10.5.3")
    ("BREAK" . "https://www.maclisp.info/pitmanual/repl.html#4.3.2")
    ("*BREAK" . "https://www.maclisp.info/pitmanual/repl.html#4.3.1")
    ("CADR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDDR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CAAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CAAAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CAADR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CADAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CADDR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDAAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDADR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDDAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDDDR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CAAAAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CAAADR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CAADAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CAADDR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CADAAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CADADR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CADDAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CADDDR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDAAAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDAADR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDADAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDADDR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDDAAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDDADR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDDDAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CDDDDR" . "https://www.maclisp.info/pitmanual/list.html#8.3.6")
    ("CAR" . "https://www.maclisp.info/pitmanual/list.html#8.3.4")
    ("CDR" . "https://www.maclisp.info/pitmanual/list.html#8.3.5")
    ("CERROR" . "https://www.maclisp.info/pitmanual/error.html#21.1.4")
    ("CGOLREAD" . "https://www.maclisp.info/pitmanual/io.html#16.48.2")
    ("CHARPOS" . "https://www.maclisp.info/pitmanual/io.html#16.7.2")
    ("CLEAR-INPUT" . "https://www.maclisp.info/pitmanual/io.html#16.10.1")
    ("CLEAR-OUTPUT" . "https://www.maclisp.info/pitmanual/io.html#16.10.2")
    ("CLOSE" . "https://www.maclisp.info/pitmanual/io.html#16.9.1")
    ("CNAMEF" . "https://www.maclisp.info/pitmanual/io.html#16.9.2")
    ("CONS" . "https://www.maclisp.info/pitmanual/list.html#8.3.1")
    ("COPYSYMBOL" . "https://www.maclisp.info/pitmanual/symbol.html#10.10.3")
    ("COS" . "https://www.maclisp.info/pitmanual/number.html#9.49.2")
    ("COUTPUT" . "https://www.maclisp.info/pitmanual/complr.html#23.2.2")
    ("CREATE-JOB" . "https://www.maclisp.info/pitmanual/intrnl.html#26.17")
    ("CURSORPOS" . "https://www.maclisp.info/pitmanual/io.html#16.7.3")
    ("CXR" . "https://www.maclisp.info/pitmanual/hunks.html#13.3.5")
    ("DEFAULTF" . "https://www.maclisp.info/pitmanual/files.html#19.3.1")
    ("DEFPROP" . "https://www.maclisp.info/pitmanual/def.html#7.2.3")
    ("DELETE" . "https://www.maclisp.info/pitmanual/list.html#8.9.1")
    ("DELETEF" . "https://www.maclisp.info/pitmanual/files.html#19.5.3")
    ("*DELETE" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.5")
    ("DELQ" . "https://www.maclisp.info/pitmanual/list.html#8.9.2")
    ("*DELQ" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.6")
    ("DEPOSIT" . "https://www.maclisp.info/pitmanual/system.html#24.14.5")
    ("DEPOSIT-BYTE" . "https://www.maclisp.info/pitmanual/bits.html#15.6.1")
    ("*DEPOSIT-BYTE" . "https://www.maclisp.info/pitmanual/bits.html#15.7.1")
    ("DESCRIBE" . "https://www.maclisp.info/pitmanual/debug.html#22.1")
    ("DIFFERENCE" . "https://www.maclisp.info/pitmanual/number.html#9.10")
    ("*DIF" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.17")
    ("DIRECTORY" . "https://www.maclisp.info/pitmanual/files.html#19.6.4")
    ("DISPLACE" . "https://www.maclisp.info/pitmanual/list.html#8.14.3")
    ("DPB" . "https://www.maclisp.info/pitmanual/bits.html#15.6.3")
    ("*DPB" . "https://www.maclisp.info/pitmanual/bits.html#15.7.3")
    ("DUMPARRAYS" . "https://www.maclisp.info/pitmanual/array.html#12.7.1")
    ("ENDPAGEFN" . "https://www.maclisp.info/pitmanual/io.html#16.11.1")
    ("EOFFN" . "https://www.maclisp.info/pitmanual/io.html#16.11.2")
    ("EQ" . "https://www.maclisp.info/pitmanual/typep.html#2.3.1")
    ("EQUAL" . "https://www.maclisp.info/pitmanual/typep.html#2.3.2")
    ("ERRFRAME" . "https://www.maclisp.info/pitmanual/error.html#21.6.1")
    ("ERROR" . "https://www.maclisp.info/pitmanual/error.html#21.1.1")
    ("ERRPRINT" . "https://www.maclisp.info/pitmanual/error.html#21.6.3")
    ("EVAL" . "https://www.maclisp.info/pitmanual/eval.html#3.4")
    ("EVALFRAME" . "https://www.maclisp.info/pitmanual/debug.html#22.5.1")
    ("EVALHOOK" . "https://www.maclisp.info/pitmanual/debug.html#22.8.1")
    ("*EVAL" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.2")
    ("EXAMINE" . "https://www.maclisp.info/pitmanual/system.html#24.14.4")
    ("EXP" . "https://www.maclisp.info/pitmanual/number.html#9.23")
    ("EXPLODE" . "https://www.maclisp.info/pitmanual/charac.html#11.3.4")
    ("EXPLODEC" . "https://www.maclisp.info/pitmanual/charac.html#11.3.2")
    ("EXPLODEN" . "https://www.maclisp.info/pitmanual/charac.html#11.3.1")
    ("*EXPR" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("EXPT" . "https://www.maclisp.info/pitmanual/number.html#9.20")
    ("FASLP" . "https://www.maclisp.info/pitmanual/files.html#19.4.2")
    ("FERROR" . "https://www.maclisp.info/pitmanual/error.html#21.1.5")
    ("*FEXPR" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("FILEP" . "https://www.maclisp.info/pitmanual/io.html#16.4.1")
    ("FILEPOS" . "https://www.maclisp.info/pitmanual/io.html#16.7.1")
    ("FILLARRAY" . "https://www.maclisp.info/pitmanual/array.html#12.5.1")
    ("FIX" . "https://www.maclisp.info/pitmanual/number.html#9.2.1")
    ("FIXNUM" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("FIXNUM-IDENTITY" . "https://www.maclisp.info/pitmanual/complr.html#23.1.9")
    ("FIXNUMP" . "https://www.maclisp.info/pitmanual/number.html#9.3.2")
    ("FIXP" . "https://www.maclisp.info/pitmanual/number.html#9.3.4")
    ("FLATC" . "https://www.maclisp.info/pitmanual/io.html#16.33.1")
    ("FLATSIZE" . "https://www.maclisp.info/pitmanual/io.html#16.33.2")
    ("FLATTEN-SYMS" . "https://www.maclisp.info/pitmanual/intrnl.html#26.9.6")
    ("FLOAT" . "https://www.maclisp.info/pitmanual/number.html#9.2.3")
    ("FLOATP" . "https://www.maclisp.info/pitmanual/number.html#9.3.5")
    ("FLONUM" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("FLONUM-IDENTITY" . "https://www.maclisp.info/pitmanual/complr.html#23.1.10")
    ("FORCE-OUTPUT" . "https://www.maclisp.info/pitmanual/io.html#16.10.3")
    ("FORMAT" . "https://www.maclisp.info/pitmanual/io.html#16.12.1")
    ("?FORMAT" . "https://www.maclisp.info/pitmanual/io.html#16.25.1")
    ("FRETRY" . "https://www.maclisp.info/pitmanual/debug.html#22.6.1")
    ("FRETURN" . "https://www.maclisp.info/pitmanual/debug.html#22.6.2")
    ("FSC" . "https://www.maclisp.info/pitmanual/bits.html#15.4.3")
    ("FUNCALL" . "https://www.maclisp.info/pitmanual/eval.html#3.9.1")
    ("GC" . "https://www.maclisp.info/pitmanual/system.html#24.18.1")
    ("GCD" . "https://www.maclisp.info/pitmanual/number.html#9.44")
    ("GCPROTECT" . "https://www.maclisp.info/pitmanual/system.html#24.18.2")
    ("GENSYM" . "https://www.maclisp.info/pitmanual/symbol.html#10.10.4")
    ("GET" . "https://www.maclisp.info/pitmanual/symbol.html#10.6.3")
    ("GETCHAR" . "https://www.maclisp.info/pitmanual/charac.html#11.2.2")
    ("GETCHARN" . "https://www.maclisp.info/pitmanual/charac.html#11.2.3")
    ("GETDDTSYM" . "https://www.maclisp.info/pitmanual/system.html#24.14.1")
    ("GETL" . "https://www.maclisp.info/pitmanual/symbol.html#10.6.4")
    ("GETMIDASOP" . "https://www.maclisp.info/pitmanual/intrnl.html#26.18.2")
    ("GETSP" . "https://www.maclisp.info/pitmanual/system.html#24.30.4")
    ("GREATERP" . "https://www.maclisp.info/pitmanual/number.html#9.35")
    ("*GREAT" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.20")
    ("^G" . "https://www.maclisp.info/pitmanual/contro.html#5.12.1")
    ("HAIPART" . "https://www.maclisp.info/pitmanual/bits.html#15.5.1")
    ("HAULONG" . "https://www.maclisp.info/pitmanual/bits.html#15.5.2")
    ("HUNK" . "https://www.maclisp.info/pitmanual/hunks.html#13.3.1")
    ("HUNKP" . "https://www.maclisp.info/pitmanual/hunks.html#13.3.3")
    ("HUNKSIZE" . "https://www.maclisp.info/pitmanual/hunks.html#13.3.4")
    ("IFIX" . "https://www.maclisp.info/pitmanual/number.html#9.2.2")
    ("IMPLODE" . "https://www.maclisp.info/pitmanual/charac.html#11.3.5")
    ("IN" . "https://www.maclisp.info/pitmanual/io.html#16.29.1")
    ("INCLUDEF" . "https://www.maclisp.info/pitmanual/files.html#19.2.5")
    ("INPUSH" . "https://www.maclisp.info/pitmanual/io.html#16.26.1")
    ("INTERN" . "https://www.maclisp.info/pitmanual/symbol.html#10.9.3")
    ("+INTERNAL-AUTOLOAD" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.1")
    ("+INTERNAL-^B-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.15.1")
    ("+INTERNAL-CARCDRP" . "https://www.maclisp.info/pitmanual/intrnl.html#26.11")
    ("+INTERNAL-DUP-P" . "https://www.maclisp.info/pitmanual/intrnl.html#26.12")
    ("+INTERNAL-FAC-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.3")
    ("+INTERNAL-GCL-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.4")
    ("+INTERNAL-GCO-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.5")
    ("+INTERNAL-INCLUDE-EOFFN" . "https://www.maclisp.info/pitmanual/intrnl.html#26.5.2")
    ("+INTERNAL-IOL-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.6")
    ("+INTERNAL-LOSSAGE" . "https://www.maclisp.info/pitmanual/intrnl.html#26.19")
    ("+INTERNAL-PDL-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.7")
    ("+INTERNAL-^Q-MACRO" . "https://www.maclisp.info/pitmanual/intrnl.html#26.15.2")
    ("+INTERNAL-*RSET-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.2")
    ("+INTERNAL-^S-MACRO" . "https://www.maclisp.info/pitmanual/intrnl.html#26.15.3")
    ("+INTERNAL-TTY-ENDPAGEFN" . "https://www.maclisp.info/pitmanual/intrnl.html#26.5.1")
    ("+INTERNAL-TTYSCAN-SUBR" . "https://www.maclisp.info/pitmanual/intrnl.html#26.6.1")
    ("+INTERNAL-UBV-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.8")
    ("+INTERNAL-UDF-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.9")
    ("+INTERNAL-UGT-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.10")
    ("+INTERNAL-UREAD-EOFFN" . "https://www.maclisp.info/pitmanual/intrnl.html#26.5.3")
    ("+INTERNAL-WNA-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.11")
    ("+INTERNAL-WTA-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.12")
    ("LAP-A-LIST" . "https://www.maclisp.info/pitmanual/intrnl.html#26.18.4")
    ("LAST" . "https://www.maclisp.info/pitmanual/list.html#8.6.1")
    ("LDB" . "https://www.maclisp.info/pitmanual/bits.html#15.6.4")
    ("*LDB" . "https://www.maclisp.info/pitmanual/bits.html#15.7.4")
    ("LENGTH" . "https://www.maclisp.info/pitmanual/list.html#8.4.4")
    ("LENGTHF" . "https://www.maclisp.info/pitmanual/files.html#19.4.1")
    ("LESSP" . "https://www.maclisp.info/pitmanual/number.html#9.37")
    ("*LESS" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.19")
    ("LEXPR-FUNCALL" . "https://www.maclisp.info/pitmanual/eval.html#3.9.2")
    ("*LEXPR" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("LH|" . "https://www.maclisp.info/pitmanual/system.html#24.14.3")
    ("LINEL" . "https://www.maclisp.info/pitmanual/io.html#16.5.2")
    ("LINENUM" . "https://www.maclisp.info/pitmanual/io.html#16.5.5")
    ("LISPT" . "https://www.maclisp.info/pitmanual/edit.html#25.2.2")
    ("LIST" . "https://www.maclisp.info/pitmanual/list.html#8.4.1")
    ("LIST*" . "https://www.maclisp.info/pitmanual/list.html#8.4.2")
    ("LISTARRAY" . "https://www.maclisp.info/pitmanual/array.html#12.5.2")
    ("LISTEN" . "https://www.maclisp.info/pitmanual/io.html#16.31.1")
    ("LISTIFY" . "https://www.maclisp.info/pitmanual/def.html#7.3.2")
    ("LISTP" . "https://www.maclisp.info/pitmanual/list.html#8.5.2")
    ("LOAD" . "https://www.maclisp.info/pitmanual/files.html#19.2.1")
    ("LOAD-BYTE" . "https://www.maclisp.info/pitmanual/bits.html#15.6.2")
    ("LOADARRAYS" . "https://www.maclisp.info/pitmanual/array.html#12.7.2")
    ("*LOAD-BYTE" . "https://www.maclisp.info/pitmanual/bits.html#15.7.2")
    ("LOG" . "https://www.maclisp.info/pitmanual/number.html#9.27")
    ("LOGAND" . "https://www.maclisp.info/pitmanual/bits.html#15.2.1")
    ("LOGIOR" . "https://www.maclisp.info/pitmanual/bits.html#15.2.2")
    ("LOGNOT" . "https://www.maclisp.info/pitmanual/bits.html#15.2.4")
    ("LOGXOR" . "https://www.maclisp.info/pitmanual/bits.html#15.2.3")
    ("LSH" . "https://www.maclisp.info/pitmanual/bits.html#15.4.1")
    ("MACROEXPAND" . "https://www.maclisp.info/pitmanual/def.html#7.8.1")
    ("MACROEXPAND-1" . "https://www.maclisp.info/pitmanual/def.html#7.8.2")
    ("MACROEXPAND-1*" . "https://www.maclisp.info/pitmanual/def.html#7.8.3")
    ("MAKE-LIST" . "https://www.maclisp.info/pitmanual/list.html#8.4.3")
    ("MAKHUNK" . "https://www.maclisp.info/pitmanual/hunks.html#13.3.2")
    ("MAKNAM" . "https://www.maclisp.info/pitmanual/symbol.html#10.10.2")
    ("MAKNUM" . "https://www.maclisp.info/pitmanual/system.html#24.15.2")
    ("MAKUNBOUND" . "https://www.maclisp.info/pitmanual/symbol.html#10.5.4")
    ("MAP" . "https://www.maclisp.info/pitmanual/list.html#8.10.1")
    ("MAPALLFILES" . "https://www.maclisp.info/pitmanual/files.html#19.6.3")
    ("MAPATOMS" . "https://www.maclisp.info/pitmanual/symbol.html#10.9.2")
    ("MAPC" . "https://www.maclisp.info/pitmanual/list.html#8.11.1")
    ("MAPCAN" . "https://www.maclisp.info/pitmanual/list.html#8.11.3")
    ("MAPCAR" . "https://www.maclisp.info/pitmanual/list.html#8.11.2")
    ("MAPCON" . "https://www.maclisp.info/pitmanual/list.html#8.10.3")
    ("MAPDIRECTORY" . "https://www.maclisp.info/pitmanual/files.html#19.6.5")
    ("MAPLIST" . "https://www.maclisp.info/pitmanual/list.html#8.10.2")
    ("MAX" . "https://www.maclisp.info/pitmanual/number.html#9.47")
    ("MEMBER" . "https://www.maclisp.info/pitmanual/list.html#8.12.1")
    ("MEMQ" . "https://www.maclisp.info/pitmanual/list.html#8.12.2")
    ("MERGEF" . "https://www.maclisp.info/pitmanual/files.html#19.3.4")
    ("MIN" . "https://www.maclisp.info/pitmanual/number.html#9.48")
    ("MINUS" . "https://www.maclisp.info/pitmanual/number.html#9.11")
    ("MINUSP" . "https://www.maclisp.info/pitmanual/number.html#9.41")
    ("MUNKAM" . "https://www.maclisp.info/pitmanual/system.html#24.15.3")
    ("NAMELIST" . "https://www.maclisp.info/pitmanual/files.html#19.3.5")
    ("NAMESTRING" . "https://www.maclisp.info/pitmanual/files.html#19.3.6")
    ("NCONC" . "https://www.maclisp.info/pitmanual/list.html#8.13.1")
    ("*NCONC" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.4")
    ("NCONS" . "https://www.maclisp.info/pitmanual/list.html#8.3.2")
    ("NOINTERRUPT" . "https://www.maclisp.info/pitmanual/system.html#24.4.1")
    ("*NOPOINT" . "https://www.maclisp.info/pitmanual/io.html#16.6.1")
    ("NORET" . "https://www.maclisp.info/pitmanual/system.html#24.30.5")
    ("NOT" . "https://www.maclisp.info/pitmanual/contro.html#5.5.1")
    ("NOUUO" . "https://www.maclisp.info/pitmanual/debug.html#22.3.2")
    ("NRECONC" . "https://www.maclisp.info/pitmanual/list.html#8.13.3")
    ("NREVERSE" . "https://www.maclisp.info/pitmanual/list.html#8.13.2")
    ("NTH" . "https://www.maclisp.info/pitmanual/list.html#8.6.2")
    ("NTHCDR" . "https://www.maclisp.info/pitmanual/list.html#8.6.3")
    ("NULL" . "https://www.maclisp.info/pitmanual/list.html#8.5.1")
    ("NUMBERP" . "https://www.maclisp.info/pitmanual/number.html#9.3.1")
    ("ODDP" . "https://www.maclisp.info/pitmanual/number.html#9.46")
    ("OPEN" . "https://www.maclisp.info/pitmanual/io.html#16.8.1")
    ("OUT" . "https://www.maclisp.info/pitmanual/io.html#16.29.2")
    ("PAGEBPORG" . "https://www.maclisp.info/pitmanual/system.html#24.30.3")
    ("PAGEL" . "https://www.maclisp.info/pitmanual/io.html#16.5.4")
    ("PAGENUM" . "https://www.maclisp.info/pitmanual/io.html#16.5.6")
    ("PAIRP" . "https://www.maclisp.info/pitmanual/list.html#8.5.3")
    ("PLIST" . "https://www.maclisp.info/pitmanual/symbol.html#10.6.6")
    ("PLUS" . "https://www.maclisp.info/pitmanual/number.html#9.4")
    ("PLUSP" . "https://www.maclisp.info/pitmanual/number.html#9.39")
    ("*PLUS" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.15")
    ("PNGET" . "https://www.maclisp.info/pitmanual/symbol.html#10.7.1")
    ("PNPUT" . "https://www.maclisp.info/pitmanual/symbol.html#10.7.2")
    ("PRIN1" . "https://www.maclisp.info/pitmanual/io.html#16.28.1")
    ("PRINC" . "https://www.maclisp.info/pitmanual/io.html#16.28.2")
    ("*PRINC" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.8")
    ("PRINT" . "https://www.maclisp.info/pitmanual/io.html#16.28.3")
    ("*PRINT" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.9")
    ("*PRIN1" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.7")
    ("PROBEF" . "https://www.maclisp.info/pitmanual/files.html#19.5.1")
    ("PURCOPY" . "https://www.maclisp.info/pitmanual/system.html#24.31.4")
    ("PURIFY" . "https://www.maclisp.info/pitmanual/system.html#24.31.6")
    ("PUTDDTSYM" . "https://www.maclisp.info/pitmanual/system.html#24.14.2")
    ("PUTPROP" . "https://www.maclisp.info/pitmanual/symbol.html#10.6.2")
    ("QMARK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.7")
    ("QUIT" . "https://www.maclisp.info/pitmanual/contro.html#5.12.2")
    ("QUOTIENT" . "https://www.maclisp.info/pitmanual/number.html#9.24")
    ("*QUO" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.18")
    ("RANDOM" . "https://www.maclisp.info/pitmanual/number.html#9.50.1")
    ("READ" . "https://www.maclisp.info/pitmanual/io.html#16.27.1")
    ("READ-*-EVAL-PRINT" . "https://www.maclisp.info/pitmanual/intrnl.html#26.2.2")
    ("READ-EVAL-*-PRINT" . "https://www.maclisp.info/pitmanual/intrnl.html#26.2.3")
    ("READ-EVAL-PRINT-*" . "https://www.maclisp.info/pitmanual/intrnl.html#26.2.4")
    ("READCH" . "https://www.maclisp.info/pitmanual/io.html#16.27.7")
    ("*READCH" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.13")
    ("*-READ-EVAL-PRINT" . "https://www.maclisp.info/pitmanual/intrnl.html#26.2.1")
    ("READLINE" . "https://www.maclisp.info/pitmanual/io.html#16.27.2")
    ("READLIST" . "https://www.maclisp.info/pitmanual/io.html#16.27.4")
    ("*READ" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.12")
    ("*REARRAY" . "https://www.maclisp.info/pitmanual/array.html#12.3.3")
    ("RECLAIM" . "https://www.maclisp.info/pitmanual/system.html#24.18.7")
    ("REMAINDER" . "https://www.maclisp.info/pitmanual/number.html#9.25")
    ("REMOB" . "https://www.maclisp.info/pitmanual/symbol.html#10.9.4")
    ("REMPROP" . "https://www.maclisp.info/pitmanual/symbol.html#10.6.5")
    ("RENAMEF" . "https://www.maclisp.info/pitmanual/files.html#19.5.2")
    ("REVERSE" . "https://www.maclisp.info/pitmanual/list.html#8.7.2")
    ("ROT" . "https://www.maclisp.info/pitmanual/bits.html#15.4.4")
    ("RPLACA" . "https://www.maclisp.info/pitmanual/list.html#8.14.1")
    ("RPLACD" . "https://www.maclisp.info/pitmanual/list.html#8.14.2")
    ("RPLACX" . "https://www.maclisp.info/pitmanual/hunks.html#13.3.6")
    ("*RSET" . "https://www.maclisp.info/pitmanual/debug.html#22.2.2")
    ("RUBOUT" . "https://www.maclisp.info/pitmanual/io.html#16.31.2")
    ("RUNTIME" . "https://www.maclisp.info/pitmanual/system.html#24.11.1")
    ("SAMEPNAMEP" . "https://www.maclisp.info/pitmanual/symbol.html#10.8.1")
    ("SASSOC" . "https://www.maclisp.info/pitmanual/list.html#8.8.3")
    ("SASSQ" . "https://www.maclisp.info/pitmanual/list.html#8.8.4")
    ("SET" . "https://www.maclisp.info/pitmanual/symbol.html#10.5.1")
    ("SETARG" . "https://www.maclisp.info/pitmanual/def.html#7.3.3")
    ("SETPLIST" . "https://www.maclisp.info/pitmanual/symbol.html#10.6.7")
    ("SETSYNTAX" . "https://www.maclisp.info/pitmanual/syntax.html#20.1")
    ("SETSYNTAX-SHARP-MACRO" . "https://www.maclisp.info/pitmanual/syntax.html#20.28.1")
    ("SFA-CALL" . "https://www.maclisp.info/pitmanual/sfa.html#17.3.2")
    ("SFA-CREATE" . "https://www.maclisp.info/pitmanual/sfa.html#17.3.1")
    ("SFA-GET" . "https://www.maclisp.info/pitmanual/sfa.html#17.4.1")
    ("SFA-STORE" . "https://www.maclisp.info/pitmanual/sfa.html#17.4.2")
    ("SFAP" . "https://www.maclisp.info/pitmanual/sfa.html#17.2")
    ("SHORTNAMESTRING" . "https://www.maclisp.info/pitmanual/files.html#19.3.7")
    ("SIN" . "https://www.maclisp.info/pitmanual/number.html#9.49.3")
    ("SLEEP" . "https://www.maclisp.info/pitmanual/system.html#24.3.3")
    ("SORT" . "https://www.maclisp.info/pitmanual/list.html#8.15.1")
    ("SORTCAR" . "https://www.maclisp.info/pitmanual/list.html#8.15.2")
    ("SPECIAL" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("SPRIN1" . "https://www.maclisp.info/pitmanual/io.html#16.46.3")
    ("SPRINTER" . "https://www.maclisp.info/pitmanual/io.html#16.46.2")
    ("SQOZ|" . "https://www.maclisp.info/pitmanual/intrnl.html#26.18.1")
    ("SQRT" . "https://www.maclisp.info/pitmanual/number.html#9.26")
    ("STRINGP" . "https://www.maclisp.info/pitmanual/string.html#14.3")
    ("STRUCT-TYPEP" . "https://www.maclisp.info/pitmanual/intrnl.html#26.13.3")
    ("SUB1" . "https://www.maclisp.info/pitmanual/number.html#9.14")
    ("SUBLIS" . "https://www.maclisp.info/pitmanual/list.html#8.16.1")
    ("SUBR" . "https://www.maclisp.info/pitmanual/debug.html#22.10.1")
    ("SUBRP" . "https://www.maclisp.info/pitmanual/eval.html#3.9.5")
    ("SUBST" . "https://www.maclisp.info/pitmanual/list.html#8.16.3")
    ("SUSPEND" . "https://www.maclisp.info/pitmanual/system.html#24.12.1")
    ("SXHASH" . "https://www.maclisp.info/pitmanual/system.html#24.16.1")
    ("SYMBOLCONC" . "https://www.maclisp.info/pitmanual/symbol.html#10.10.1")
    ("SYMBOLP" . "https://www.maclisp.info/pitmanual/symbol.html#10.2")
    ("SYMEVAL" . "https://www.maclisp.info/pitmanual/symbol.html#10.5.2")
    ("SYSCALL" . "https://www.maclisp.info/pitmanual/system.html#24.13.1")
    ("SYSP" . "https://www.maclisp.info/pitmanual/system.html#24.18.6")
    ("TERPRI" . "https://www.maclisp.info/pitmanual/io.html#16.28.4")
    ("*TERPRI" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.10")
    ("*THROW" . "https://www.maclisp.info/pitmanual/contro.html#5.13.2")
    ("TIME" . "https://www.maclisp.info/pitmanual/system.html#24.11.2")
    ("TIMES" . "https://www.maclisp.info/pitmanual/number.html#9.17")
    ("*TIMES" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.16")
    ("TRUENAME" . "https://www.maclisp.info/pitmanual/files.html#19.3.3")
    ("TYI" . "https://www.maclisp.info/pitmanual/io.html#16.27.3")
    ("TYIPEEK" . "https://www.maclisp.info/pitmanual/io.html#16.27.8")
    ("*TYI" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.14")
    ("TYO" . "https://www.maclisp.info/pitmanual/io.html#16.30.1")
    ("*TYO" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.11")
    ("+TYO" . "https://www.maclisp.info/pitmanual/io.html#16.30.2")
    ("TYPEP" . "https://www.maclisp.info/pitmanual/typep.html#2.1.2")
    ("UNSPECIAL" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("UNTYI" . "https://www.maclisp.info/pitmanual/io.html#16.27.9")
    ("VALRET" . "https://www.maclisp.info/pitmanual/system.html#24.13.2")
    ("VALUE-CELL-LOCATION" . "https://www.maclisp.info/pitmanual/system.html#24.15.1")
    ("XCONS" . "https://www.maclisp.info/pitmanual/list.html#8.3.3")
    ("Y-OR-N-P" . "https://www.maclisp.info/pitmanual/io.html#16.27.5")
    ("YES-OR-NO-P" . "https://www.maclisp.info/pitmanual/io.html#16.27.6")
    ("ZEROP" . "https://www.maclisp.info/pitmanual/number.html#9.40")
    ("*" . "https://www.maclisp.info/pitmanual/number.html#9.18")
    ("*$" . "https://www.maclisp.info/pitmanual/number.html#9.19")
    ("*-READ-EVAL-PRINT" . "https://www.maclisp.info/pitmanual/intrnl.html#26.2.1")
    ("*APPEND" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.3")
    ("*APPLY" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.1")
    ("*ARRAY" . "https://www.maclisp.info/pitmanual/array.html#12.3.1")
    ("*BREAK" . "https://www.maclisp.info/pitmanual/repl.html#4.3.1")
    ("*DELETE" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.5")
    ("*DELQ" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.6")
    ("*DEPOSIT-BYTE" . "https://www.maclisp.info/pitmanual/bits.html#15.7.1")
    ("*DIF" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.17")
    ("*DPB" . "https://www.maclisp.info/pitmanual/bits.html#15.7.3")
    ("*EVAL" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.2")
    ("*EXPR" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("*FEXPR" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("*GREAT" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.20")
    ("*LDB" . "https://www.maclisp.info/pitmanual/bits.html#15.7.4")
    ("*LESS" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.19")
    ("*LEXPR" . "https://www.maclisp.info/pitmanual/complr.html#23.1.8")
    ("*LOAD-BYTE" . "https://www.maclisp.info/pitmanual/bits.html#15.7.2")
    ("*NCONC" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.4")
    ("*NOPOINT" . "https://www.maclisp.info/pitmanual/io.html#16.6.1")
    ("*PLUS" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.15")
    ("*PRIN1" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.7")
    ("*PRINC" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.8")
    ("*PRINT" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.9")
    ("*QUO" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.18")
    ("*READ" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.12")
    ("*READCH" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.13")
    ("*REARRAY" . "https://www.maclisp.info/pitmanual/array.html#12.3.3")
    ("*RSET" . "https://www.maclisp.info/pitmanual/debug.html#22.2.2")
    ("*TERPRI" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.10")
    ("*THROW" . "https://www.maclisp.info/pitmanual/contro.html#5.13.2")
    ("*TIMES" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.16")
    ("*TYI" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.14")
    ("*TYO" . "https://www.maclisp.info/pitmanual/intrnl.html#26.3.11")
    ("+" . "https://www.maclisp.info/pitmanual/number.html#9.5")
    ("+$" . "https://www.maclisp.info/pitmanual/number.html#9.6")
    ("+INTERNAL-*RSET-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.2")
    ("+INTERNAL-AUTOLOAD" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.1")
    ("+INTERNAL-CARCDRP" . "https://www.maclisp.info/pitmanual/intrnl.html#26.11")
    ("+INTERNAL-DUP-P" . "https://www.maclisp.info/pitmanual/intrnl.html#26.12")
    ("+INTERNAL-FAC-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.3")
    ("+INTERNAL-GCL-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.4")
    ("+INTERNAL-GCO-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.5")
    ("+INTERNAL-INCLUDE-EOFFN" . "https://www.maclisp.info/pitmanual/intrnl.html#26.5.2")
    ("+INTERNAL-IOL-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.6")
    ("+INTERNAL-LOSSAGE" . "https://www.maclisp.info/pitmanual/intrnl.html#26.19")
    ("+INTERNAL-PDL-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.7")
    ("+INTERNAL-TTY-ENDPAGEFN" . "https://www.maclisp.info/pitmanual/intrnl.html#26.5.1")
    ("+INTERNAL-TTYSCAN-SUBR" . "https://www.maclisp.info/pitmanual/intrnl.html#26.6.1")
    ("+INTERNAL-UBV-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.8")
    ("+INTERNAL-UDF-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.9")
    ("+INTERNAL-UGT-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.10")
    ("+INTERNAL-UREAD-EOFFN" . "https://www.maclisp.info/pitmanual/intrnl.html#26.5.3")
    ("+INTERNAL-WNA-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.11")
    ("+INTERNAL-WTA-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.4.12")
    ("+INTERNAL-^B-BREAK" . "https://www.maclisp.info/pitmanual/intrnl.html#26.15.1")
    ("+INTERNAL-^Q-MACRO" . "https://www.maclisp.info/pitmanual/intrnl.html#26.15.2")
    ("+INTERNAL-^S-MACRO" . "https://www.maclisp.info/pitmanual/intrnl.html#26.15.3")
    ("+TYO" . "https://www.maclisp.info/pitmanual/io.html#16.30.2")
    ("-" . "https://www.maclisp.info/pitmanual/number.html#9.12")
    ("-$" . "https://www.maclisp.info/pitmanual/number.html#9.13")
    ("/" . "https://www.maclisp.info/pitmanual/number.html#9.30")
    ("/$" . "https://www.maclisp.info/pitmanual/number.html#9.31")
    ("1+" . "https://www.maclisp.info/pitmanual/number.html#9.8")
    ("1+$" . "https://www.maclisp.info/pitmanual/number.html#9.9")
    ("1-" . "https://www.maclisp.info/pitmanual/number.html#9.15")
    ("1-$" . "https://www.maclisp.info/pitmanual/number.html#9.16")
    ("&lt;" . "https://www.maclisp.info/pitmanual/number.html#9.38")
    ("=" . "https://www.maclisp.info/pitmanual/number.html#9.34")
    (">" . "https://www.maclisp.info/pitmanual/number.html#9.36")
    ("?FORMAT" . "https://www.maclisp.info/pitmanual/io.html#16.25.1")
    ("\\" . "https://www.maclisp.info/pitmanual/number.html#9.32")
    ("\\\\" . "https://www.maclisp.info/pitmanual/number.html#9.45")
    ("^" . "https://www.maclisp.info/pitmanual/number.html#9.21")
    ("^$" . "https://www.maclisp.info/pitmanual/number.html#9.22")
    ("^G" . "https://www.maclisp.info/pitmanual/contro.html#5.12.1")))