#lang racket

(require nanopass/base)
(provide HTML)

;;;; Target language of formatting

(define-language HTML
  (terminals (list (attributes))
             (string (s)))
  (Node (n)
        (text s)
        (a attributes n ...)
        (abbr attributes n ...)
        (address attributes n ...)
        (area attributes n ...)
        (article attributes n ...)
        (aside attributes n ...)
        (audio attributes n ...)
        (b attributes n ...)
        (base attributes n ...)
        (bdi attributes n ...)
        (bdo attributes n ...)
        (blockquote attributes n ...)
        (body attributes n ...)
        (br attributes n ...)
        (button attributes n ...)
        (canvas attributes n ...)
        (caption attributes n ...)
        (cite attributes n ...)
        (code attributes n ...)
        (col attributes n ...)
        (colgroup attributes n ...)
        (data attributes n ...)
        (datalist attributes n ...)
        (dd attributes n ...)
        (del attributes n ...)
        (details attributes n ...)
        (dfn attributes n ...)
        (dialog attributes n ...)
        (div attributes n ...)
        (dl attributes n ...)
        (dt attributes n ...)
        (em attributes n ...)
        (embed attributes n ...)
        (fieldset attributes n ...)
        (figcaption attributes n ...)
        (figure attributes n ...)
        (footer attributes n ...)
        (form attributes n ...)
        (h1 attributes n ...)
        (h2 attributes n ...)
        (h3 attributes n ...)
        (h4 attributes n ...)
        (h5 attributes n ...)
        (h6 attributes n ...)
        (head attributes n ...)
        (header attributes n ...)
        (hgroup attributes n ...)
        (hr attributes n ...)
        (html attributes n ...)
        (i attributes n ...)
        (iframe attributes n ...)
        (img attributes n ...)
        (input attributes n ...)
        (ins attributes n ...)
        (kbd attributes n ...)
        (label attributes n ...)
        (legend attributes n ...)
        (li attributes n ...)
        (link attributes n ...)
        (main attributes n ...)
        (map attributes n ...)
        (mark attributes n ...)
        (menu attributes n ...)
        (meta attributes n ...)
        (meter attributes n ...)
        (nav attributes n ...)
        (noscript attributes n ...)
        (object attributes n ...)
        (ol attributes n ...)
        (optgroup attributes n ...)
        (option attributes n ...)
        (output attributes n ...)
        (p attributes n ...)
        (picture attributes n ...)
        (pre attributes n ...)
        (progress attributes n ...)
        (q attributes n ...)
        (rp attributes n ...)
        (rt attributes n ...)
        (ruby attributes n ...)
        (s attributes n ...)
        (samp attributes n ...)
        (search attributes n ...)
        (script attributes n ...)
        (section attributes n ...)
        (select attributes n ...)
        (selectedcontent attributes n ...)
        (slot attributes n ...)
        (small attributes n ...)
        (source attributes n ...)
        (span attributes n ...)
        (strong attributes n ...)
        (style attributes n ...)
        (sub attributes n ...)
        (summary attributes n ...)
        (sup attributes n ...)
        (table attributes n ...)
        (tbody attributes n ...)
        (td attributes n ...)
        (template attributes n ...)
        (textarea attributes n ...)
        (tfoot attributes n ...)
        (th attributes n ...)
        (thead attributes n ...)
        (time attributes n ...)
        (title attributes n ...)
        (tr attributes n ...)
        (track attributes n ...)
        (u attributes n ...)
        (ul attributes n ...)
        (var attributes n ...)
        (video attributes n ...)
        (wbr attributes n ...)))